# Generated by Django 4.1.2 on 2022-10-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_attendance_attendance_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Subject_id',
            new_name='subject_id',
        ),
    ]
