# Generated by Django 4.1.2 on 2022-11-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_studentpatient_studentdesign_studentcopywrite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Nptel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nptel_course', models.CharField(max_length=100)),
                ('nptel_session_start', models.CharField(max_length=100)),
                ('nptel_session_end', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(null=True)),
                ('certificate_type', models.CharField(max_length=50)),
                ('upload_certificate', models.FileField(null=True, upload_to='')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Amcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_domine', models.IntegerField(null=True)),
                ('score_english', models.IntegerField(null=True)),
                ('score_logical', models.IntegerField(null=True)),
                ('score_quatitative', models.IntegerField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student')),
            ],
        ),
        migrations.CreateModel(
            name='Nptel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nptel_course', models.CharField(max_length=100)),
                ('nptel_session_start', models.CharField(max_length=100)),
                ('nptel_session_end', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(null=True)),
                ('certificate_type', models.CharField(max_length=50)),
                ('upload_certificate', models.FileField(null=True, upload_to='')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Amcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_domine', models.IntegerField(null=True)),
                ('score_english', models.IntegerField(null=True)),
                ('score_logical', models.IntegerField(null=True)),
                ('score_quatitative', models.IntegerField(null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.staff')),
            ],
        ),
    ]
